from . import crm_lead
from . import crm_sales_channel
from . import crm_skill
from . import res_partner
from . import crm_lead_stage
from . import sale_order
from . import res_users
from . import crm_looking_for
from . import sale_report
