name: Odoo Code Quality Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint-odoo flake8

    - name: Run script to get module name
      run: |
        python get_module_name.py

    - name: Run pylint-odoo
      run: |
        pylint --load-plugins=pylintodoo -d all $MODULE_NAME

    - name: Run Flake8
      run: |
        flake8 $MODULE_NAME