name: Odoo Code Quality Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint-odoo flake8

    - name: Run Python script and export MODULE_NAME
      id: extract
      run: |
        MODULE_NAME=$(python3 get_module_name.py)
        echo "MODULE_NAME=$MODULE_NAME" >> $GITHUB_ENV

    - name: Use the module name
      run: |
        echo "Extracted module: ${{ env.MODULE_NAME }}"

    - name: Run pylint-odoo
      run: |
        pylint --load-plugins=pylintodoo -d all ${{ env.MODULE_NAME }}

    - name: Run Flake8
      run: |
        flake8 ${{ env.MODULE_NAME }}